### ISSUE TITLE
Exception that occours in a call activity which is handled by an ErrorBoundaryEvent is logged

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine#109]
#### Describe your issue
Since the CallActivities use the ConsumerAPI to internally call the process, assosiated, with the CallActivity, every output that the ConsumerAPI logs gets redirected. 

This may be a problem, if you have a CallActivity with an attached ErrorBoundaryEvent in your process, like so:

<img width="1223" alt="screen shot 2018-07-02 at 13 18 35" src="https://user-images.githubusercontent.com/38498731/42161254-7c42f278-7dfa-11e8-9b50-d870b5e8caf5.png">

If the CallActivity produces an error, you get a stack trace like this:
```
error: [processengine:execute_process_service] An error occured while trying to execute process model with id "call_activity_subprocess_error" in correlation "786f1346-1bed-4b84-8076-a9b0d6e07546". Error: Unhandled subprocess exception!
    at ScriptTaskHandler.eval (eval at executeInternally (/Users/robin/Documents/process_engine/process_engine_meta/process_engine/dist/commonjs/new_model/runtime/engine/handler/script_task_handler.js:24:32), <anonymous>:3:7)
    at ScriptTaskHandler.executeInternally (/Users/robin/Documents/process_engine/process_engine_meta/process_engine/dist/commonjs/new_model/runtime/engine/handler/script_task_handler.js:25:39)
    at <anonymous>
```

This is because the ConsumerAPI has no way to find out, if a unhandled Error is somehow handled by another Process.

The issue is, that a stack trace like this looks like, the process produces an error somewhere, even if all Errors are correctly handled.

#### How can others reproduce the issue?
* Create a Process
* Add a CallActivity to the process
* Create a Process that produces an Error
* Call that process with the call activity
* Attach an ErrorBoundaryEvent to the CallActivity, that should catch the unhandled error of the CallActivity
* Look at your ProcessEngine server log output

#### Possible solution
We should discuss how the ConsumerAPI should behave, if its encounter an unhandled Error.

In every case, the Error message should be suppressed by the outer process, if the Error is handled. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I'm not really sure I understand what the issue is here. 

> every output that the ConsumerAPI logs gets redirected.

What do you mean by "redirected"?

>This is because the ConsumerAPI has no way to find out, if a unhandled Error is somehow handled by another Process.

That is because it is not the responsibility of the Consumer API to do so. It only passes the responses/errors received from the process engine back to the caller. All error handling **must** be handled by the process engine itself.

Using Call Activities doesn't invalidate this point.

> The issue is, that a stack trace like this looks like, the process produces an error somewhere, even if all Errors are correctly handled.

Logging an error doesn't mean it won't be handled.
If that were the case, you'd see one of the infamous `Unhandled Promise rejection` errors.

Logging errors is a good idea, actually, because you, as the maintainer, will see what went wrong and where.
Also keep in mind that this is a purely internal log. None of these infos are passed back to the customer.
